version: '3'

services:
  proxy:
    image: dockerflow/docker-flow-proxy:18.06.15-63-linux-arm
    ports:
      - 80:80
      - 443:443
    networks:
      - agent_network
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:18.06.03-26-linux-arm
    networks:
      - agent_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  letsencrypt-companion:
    image: holgerimbery/docker-flow-letsencrypt:latest
    networks:
      - agent_network
    environment:
      # change to meet your requirements
      - DOMAIN_1=('host1.domain.tdl')
      - DOMAIN_2=('host2.domain.tdl')
      - CERTBOT_EMAIL=name@domain.tdl
      - PROXY_ADDRESS=proxy
      - CERTBOT_CRON_RENEW=('0 3 * * *' '0 15 * * *')
    volumes:
          - letsencrypt_data:/etc/letsencrypt
        #  - /srv/letsencrypt:/etc/letsencrypt
    deploy:
      labels:
        - com.df.servicePath=/.well-known/acme-challenge
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=80
      placement:
        # change to meet node.id
        constraints: [node.role == manager]
      replicas: 1


  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        # change to meet your requirements
        - com.df.serviceDomain=host1.domain.tdl
        - com.df.httpsOnly=true
        - com.df.reqPathSearch=/portainer
        - com.df.port=9000
    command: "-H tcp://tasks.agent:9001 --tlsskipverify --templates https://raw.githubusercontent.com/holgerimbery/feeder/master/templates.json"


networks:
  agent_network:
    driver: overlay

volumes:
  portainer_data:
    external: true
  
  letsencrypt_data:
    external: true
